/// Flutter icons MyFlutterApp
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
///
/// * Brandico, (C) 2012 by Vitaly Puzrin
///         Author:    Crowdsourced, for Fontello project
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:
///
import 'package:flutter/widgets.dart';

class TwitterIcon {
  TwitterIcon._();

  static const _kFontFam = 'TwitterFont';
  static const String? _kFontPkg = null;

  static const IconData twitterBird =
      IconData(0xf303, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
