name: mynotes
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
# #enddocregion FlutterLocalizations
  # intl: ^0.17.0
# #enddocregion Intl
  cupertino_icons: ^1.0.2
  firebase_core: ^1.16.0
  firebase_auth: ^3.3.17
  cloud_firestore: ^3.1.14
  firebase_analytics: ^9.1.7
  google_sign_in: ^5.3.1
  flutter_facebook_auth: ^4.3.4
  twitter_login: ^4.2.3
  flutter_dotenv: ^5.0.2
  file_picker: ^4.5.1
  flutter_i18n: ^0.32.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  # generate: true
  uses-material-design: true

  assets:
  # Environment variables
    - .env.dev
    - .env.prod
  # Images
    - assets/images/default_avatar.jpeg
  # Load localization files
    - assets/flutter_i18n/en.json
    - assets/flutter_i18n/ja.json
    - assets/flutter_i18n/vn.json

  fonts:
    - family: TwitterFont
      fonts:
        - asset: assets/fonts/TwitterFont.ttf
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Italic-VariableFont_wght.ttf
        - asset: assets/fonts/Raleway-VariableFont_wght.ttf
          style: normal
          weight: 700
    - family: Montserrat
      fonts: 
        - asset: assets/fonts/Montserrat-Italic-VariableFont_wght.ttf
        - asset: assets/fonts/Montserrat-VariableFont_wght.ttf
          style: italic
          weight: 700
  generate: true