// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGwx2OgCITS5EQRLCQbb7w1xoCusEBqGU',
    appId: '1:633363816342:web:56211cce38d23d0fe1c7b7',
    messagingSenderId: '633363816342',
    projectId: 'flutter-scratch',
    authDomain: 'flutter-scratch.firebaseapp.com',
    storageBucket: 'flutter-scratch.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnUgdQKmCAaL596fNRuNDKDJV7KrFE9Mg',
    appId: '1:633363816342:android:121a134ec09528d2e1c7b7',
    messagingSenderId: '633363816342',
    projectId: 'flutter-scratch',
    storageBucket: 'flutter-scratch.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvndT3R6NxsxJyhEKecsBXXYfueW3yqd4',
    appId: '1:633363816342:ios:3f5374db5f04e48ce1c7b7',
    messagingSenderId: '633363816342',
    projectId: 'flutter-scratch',
    storageBucket: 'flutter-scratch.appspot.com',
    iosClientId: '633363816342-fhibhg8h0ree587eoljdks4bmi9ssja2.apps.googleusercontent.com',
    iosBundleId: 'com.example.learnFlutter',
  );
}
